language: node_js
node_js:
- stable
services:
- postgresql
script: npm test
after_success:
- npm run coveralls
env:
  global:
  - secure: kS/UZbMjvTy/lFlijArwc2rLL9+YaWag7JNrcN4nRP09V/i6ioyvXa5Qiw89fK2+GS1wcadQDzsxz07HKSNBz3epOuz+b/BwVvK2NQ2Ag0B1mEvZTkyPpsimKSue46gV1v/+v3qNG4bFfzmtjiBHHvrpaeFRJx4gKvga+KRg3H2ZNMWKH/cqwu0CeRdPXTwfUFQYnRl4gM16vJXTXX+UolUPQdLg1VodlwL0CsW3nGwKU4icuzhLZ3QHHsg2+dAvshMu0fyKvDfWeTjtioX5x/FbQUJ8cP9aVNExvQxxjce8z0zkQcvax1DMVXkJTXyQqrz0UUiDYW1qu7UwhLkR3EZ9aMn4DqXJwfkRD1j0HO7JG6/q1ygbqrPCzvrelTW/AUXt/QNMuHIJca7Wey81nrXYXVHa7G3SyoaHaPwjfmZmKZQ7aa2LYDzRFkqU5PhxQPsTIUDElEIKjNp2s3v1/Z4ZB8NqD+ZSbv374bsVq0ICTwo4AQDUyWgjp7vEd20wb/gb0L1SZIMSJ/xP95d5oiaeA5pwl02oGxMVB5wvJncDYWY6H7czj5IxWM8HsukFInVX8d6PlSIPmjZSYTqUeJvaeiq6GbAisAKdSK2cR4NaaJz0kfXyTHkpTF2d5YA+kvYp+GmbkKrBvDDus9Rp/GB7rAW4LmypPLxvxm724Sc=
  - secure: He955lz+XdD4nEsLU9mW8QdbMQfnz3oAF2+kpjxgLDgrusydyi1GAAdA5X6+uzjkPw4jwnxeXy7YPFejiqHIaZtJbEPRBQCBUQ02ZVrHnj6TtSvAJmXdw9zIX89urtJP2SdwyMboEnuuIZXObN4FcIPoqftddubtFWpYr4N90eCGPG8pLa551adZgPjL/ED1g8uFQfQB6ubzFnixoBW/tGlYD3QEfqLxn0H0GIy9BVN5RCJf7Oho9vnHZKs+cTl71Cw5jPxwsA3+WEJ8UVHVsvOybp24d1z+RHB6Xig6Z604xloeoODXGLWDxbURgI9Utg/psRM0mlPiONLaJCATLWQ6xZBkhE8NqZHsR9Swx9HHzpzCxs5jaanLhvEKCmG0fVkaJ64rHlcbUYY6+c2iJV8dvzPUWEd6e//u7KW955D6xLrR7hgVOl5o+21JEUu9msLxbFM6t+hxlIbf1TkSGmoDo316p1B1ur5kqrh72Y0GspyzNxPgSVQtA0XFU997EEmoRiJeZAuaHqzI48/d4jUF0q8L9q3bEWOG7Z57BLpiEkW1xiyQejU/cbXuCX5vjcYAKB0ccGv59S4q8CtAOTphaQnw/z8y8K7NPnG8+NTKfVPOHt0f5VXKgokD4bC4sjUABspS6pNQwSXLgKVVA87v8LyJ25GwHIfa739PAbQ=
