language: node_js
node_js:
- stable
services:
- postgresql
script: npm test
after_success:
- npm run coveralls

env:
  global:
    secure: kS/UZbMjvTy/lFlijArwc2rLL9+YaWag7JNrcN4nRP09V/i6ioyvXa5Qiw89fK2+GS1wcadQDzsxz07HKSNBz3epOuz+b/BwVvK2NQ2Ag0B1mEvZTkyPpsimKSue46gV1v/+v3qNG4bFfzmtjiBHHvrpaeFRJx4gKvga+KRg3H2ZNMWKH/cqwu0CeRdPXTwfUFQYnRl4gM16vJXTXX+UolUPQdLg1VodlwL0CsW3nGwKU4icuzhLZ3QHHsg2+dAvshMu0fyKvDfWeTjtioX5x/FbQUJ8cP9aVNExvQxxjce8z0zkQcvax1DMVXkJTXyQqrz0UUiDYW1qu7UwhLkR3EZ9aMn4DqXJwfkRD1j0HO7JG6/q1ygbqrPCzvrelTW/AUXt/QNMuHIJca7Wey81nrXYXVHa7G3SyoaHaPwjfmZmKZQ7aa2LYDzRFkqU5PhxQPsTIUDElEIKjNp2s3v1/Z4ZB8NqD+ZSbv374bsVq0ICTwo4AQDUyWgjp7vEd20wb/gb0L1SZIMSJ/xP95d5oiaeA5pwl02oGxMVB5wvJncDYWY6H7czj5IxWM8HsukFInVX8d6PlSIPmjZSYTqUeJvaeiq6GbAisAKdSK2cR4NaaJz0kfXyTHkpTF2d5YA+kvYp+GmbkKrBvDDus9Rp/GB7rAW4LmypPLxvxm724Sc=
