language: node_js
node_js:  
        - stable
services:
        - postgresql
script: npm test
after_success:
             - npm run coveralls
secure: "S3XzSmdDJbRqj9fRUiXa7w/3is+9IoG40cf8jBzc6+PVX1Eb/+RNTTVKa8TLq4PPipd4ms+7dr9Bi8OFf0sMN6v6FkMtn3LHu4H66HBMTUP/iT6vDkIqEoetgYVSVzl8N8woNEXUZP7Ta9Evnp3f0AjPsqgK8q4MJoCABlSkYAvSizTQgOjdArxEqntFlpDIhPa7WRzMEerGpUb3fuSUdqVpS9yJRcFo1KhF70NEwXXGgMVzbUttq7ZU9T7lxI2DU0b5RQ9KmsmQa3lc/01KcIN0pwj+X/P5otJJ7ZaNNYIIB9Yv9EpmK6ohpCujJOdsWmrFbbqBxCZt67+jov65It32Fyj9xqgYlt0AUnwZ8rLvwOdg6ugXWN9auLh2Yk1gdiPjRlVPzvxmC9VRN3Ycn14vXZ9/vXGnIek1aMV3pNO8rTFv6WYh5FMZdqLWGbtNxllG+Wfi/Q8sWoMXsA8P3IU5Q/vzB8MOf8+OKy97UnmJs7iVOvtM7Orxi/za/ztUhPDgakhIA9X+p6xw5Eh2mGYpfiQa2rlWcL4aQb/qMz3aUGcBHNofxcFOmzxWap6TkSXoWjNU5efaxnif2B+3FL5zM79K67Ib2UPtwnL/9Uvolegx+ez5V9mws/9DXBRbqMuyxWjPYrQo6mo+ZfxyiUaiQk8kNnuHR2svltFPqXU="