require('dotenv').config();

const cloudinary = require('cloudinary').v2;

// File upload
cloudinary.uploader.upload('image.jpg', { tags: 'gif_img' }, function (err, image) {
  console.log();
  console.log('** File Upload');
  if (err) { console.warn(err); }
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* " + image.public_id);
  console.log("* " + image.url);
  waitForAllUploads("pizza", err, image);

})
